


import Background from './_components/background';
import Footer from './_components/footer';
import './globals.css';
import NavBar from '@/app/_components/nav';



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
//   const pathname = usePathname();

  return (
    <html lang="en">
      <body>
			<Background />
			<div style={{ position: 'relative', zIndex: 1}}>
				<NavBar />
				{children}
				<Footer />
			</div>
      </body>
    </html>
  );
}
